{{ config(unique_key="lga_id", alias="g01_census_2016_nsw_lga") }}

select
    cast(substring(lga_code_2016, 4, 5) as int) as lga_id,
    tot_p_m as total_population_m,
    tot_p_f as total_population_f,
    tot_p_p as total_population_p,
    age_0_4_yr_m as age_0_4_year_m,
    age_0_4_yr_f as age_0_4_year_f,
    age_0_4_yr_p as age_0_4_year_p,
    age_5_14_yr_m as age_5_14_year_m,
    age_5_14_yr_f as age_5_14_year_f,
    age_5_14_yr_p as age_5_14_year_p,
    age_15_19_yr_m as age_15_19_year_m,
    age_15_19_yr_f as age_15_19_year_f,
    age_15_19_yr_p as age_15_19_year_p,
    age_20_24_yr_m as age_20_24_year_m,
    age_20_24_yr_f as age_20_24_year_f,
    age_20_24_yr_p as age_20_24_year_p,
    age_25_34_yr_m as age_25_34_year_m,
    age_25_34_yr_f as age_25_34_year_f,
    age_25_34_yr_p as age_25_34_year_p,
    age_35_44_yr_m as age_35_44_year_m,
    age_35_44_yr_f as age_35_44_year_f,
    age_35_44_yr_p as age_35_44_year_p,
    age_45_54_yr_m as age_45_54_year_m,
    age_45_54_yr_f as age_45_54_year_f,
    age_45_54_yr_p as age_45_54_year_p,
    age_55_64_yr_m as age_55_64_year_m,
    age_55_64_yr_f as age_55_64_year_f,
    age_55_64_yr_p as age_55_64_year_p,
    age_65_74_yr_m as age_65_74_year_m,
    age_65_74_yr_f as age_65_74_year_f,
    age_65_74_yr_p as age_65_74_year_p,
    age_75_84_yr_m as age_75_84_year_m,
    age_75_84_yr_f as age_75_84_year_f,
    age_75_84_yr_p as age_75_84_year_p,
    age_85ov_m as age_85_over_m,
    age_85ov_f as age_85_over_f,
    age_85ov_p as age_85_over_p,
    counted_census_night_home_m as count_census_night_home_m,
    counted_census_night_home_f as count_census_night_home_f,
    counted_census_night_home_p as count_census_night_home_p,
    count_census_nt_ewhere_aust_m as count_census_night_elsewhere_aus_m,
    count_census_nt_ewhere_aust_f as count_census_night_elsewhere_aus_f,
    count_census_nt_ewhere_aust_p as count_census_night_elsewhere_aus_p,
    indigenous_psns_aboriginal_m as indigenous_aboriginal_m,
    indigenous_psns_aboriginal_f as indigenous_aboriginal_f,
    indigenous_psns_aboriginal_p as indigenous_aboriginal_p,
    indig_psns_torres_strait_is_m as indigenous_torres_strait_m,
    indig_psns_torres_strait_is_f as indigenous_torres_strait_f,
    indig_psns_torres_strait_is_p as indigenous_torres_strait_p,
    indig_bth_abor_torres_st_is_m as indigenous_both_aboriginal_torres_strait_m,
    indig_bth_abor_torres_st_is_f as indigenous_both_aboriginal_torres_strait_f,
    indig_bth_abor_torres_st_is_p as indigenous_both_aboriginal_torres_strait_p,
    indigenous_p_tot_m as indigenous_total_m,
    indigenous_p_tot_f as indigenous_total_f,
    indigenous_p_tot_p as indigenous_total_p,
    birthplace_australia_m,
    birthplace_australia_f,
    birthplace_australia_p,
    birthplace_elsewhere_m,
    birthplace_elsewhere_f,
    birthplace_elsewhere_p,
    lang_spoken_home_eng_only_m as language_spoken_home_english_only_m,
    lang_spoken_home_eng_only_f as language_spoken_home_english_only_f,
    lang_spoken_home_eng_only_p as language_spoken_home_english_only_p,
    lang_spoken_home_oth_lang_m as language_spoken_home_other_m,
    lang_spoken_home_oth_lang_f as language_spoken_home_other_f,
    lang_spoken_home_oth_lang_p as language_spoken_home_other_p,
    australian_citizen_m,
    australian_citizen_f,
    australian_citizen_p,
    age_psns_att_educ_inst_0_4_m as age_attend_education_institution_0_4_m,
    age_psns_att_educ_inst_0_4_f as age_attend_education_institution_0_4_f,
    age_psns_att_educ_inst_0_4_p as age_attend_education_institution_0_4_p,
    age_psns_att_educ_inst_5_14_m as age_attend_education_institution_5_14_m,
    age_psns_att_educ_inst_5_14_f as age_attend_education_institution_5_14_f,
    age_psns_att_educ_inst_5_14_p as age_attend_education_institution_5_14_p,
    age_psns_att_edu_inst_15_19_m as age_attend_education_institution_15_19_m,
    age_psns_att_edu_inst_15_19_f as age_attend_education_institution_15_19_f,
    age_psns_att_edu_inst_15_19_p as age_attend_education_institution_15_19_p,
    age_psns_att_edu_inst_20_24_m as age_attend_education_institution_20_24_m,
    age_psns_att_edu_inst_20_24_f as age_attend_education_institution_20_24_f,
    age_psns_att_edu_inst_20_24_p as age_attend_education_institution_20_24_p,
    age_psns_att_edu_inst_25_ov_m as age_attend_education_institution_25_over_m,
    age_psns_att_edu_inst_25_ov_f as age_attend_education_institution_25_over_f,
    age_psns_att_edu_inst_25_ov_p as age_attend_education_institution_25_over_p,
    high_yr_schl_comp_yr_12_eq_m as school_year_12_completed_m,
    high_yr_schl_comp_yr_12_eq_f as school_year_12_completed_f,
    high_yr_schl_comp_yr_12_eq_p as school_year_12_completed_p,
    high_yr_schl_comp_yr_11_eq_m as school_year_11_completed_m,
    high_yr_schl_comp_yr_11_eq_f as school_year_11_completed_f,
    high_yr_schl_comp_yr_11_eq_p as school_year_11_completed_p,
    high_yr_schl_comp_yr_10_eq_m as school_year_10_completed_m,
    high_yr_schl_comp_yr_10_eq_f as school_year_10_completed_f,
    high_yr_schl_comp_yr_10_eq_p as school_year_10_completed_p,
    high_yr_schl_comp_yr_9_eq_m as school_year_9_completed_m,
    high_yr_schl_comp_yr_9_eq_f as school_year_9_completed_f,
    high_yr_schl_comp_yr_9_eq_p as school_year_9_completed_p,
    high_yr_schl_comp_yr_8_belw_m as school_year_8_below_completed_m,
    high_yr_schl_comp_yr_8_belw_f as school_year_8_below_completed_f,
    high_yr_schl_comp_yr_8_belw_p as school_year_8_below_completed_p,
    high_yr_schl_comp_d_n_g_sch_m as school_did_not_attend_school_m,
    high_yr_schl_comp_d_n_g_sch_f as school_did_not_attend_school_f,
    high_yr_schl_comp_d_n_g_sch_p as school_did_not_attend_school_p,
    count_psns_occ_priv_dwgs_m as count_private_dwellings_m,
    count_psns_occ_priv_dwgs_f as count_private_dwellings_f,
    count_psns_occ_priv_dwgs_p as count_private_dwellings_p,
    count_persons_other_dwgs_m as count_other_dwellings_m,
    count_persons_other_dwgs_f as count_other_dwellings_f,
    count_persons_other_dwgs_p as count_other_dwellings_p
from {{ ref("b_g01_census_2016_nsw_lga") }}
